# This is an example NatsCluster manifest which uses a 3rd party initContainer
# to fetch the authorization credentials from outside kubernetes.
#
# An example of this could be consul-template getting user/passwords from vault.
apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: my-nats-cluster
  namespace: nats-stuff
spec:
  size: 5
  version: "1.3.0"
  service:
    maxPayload: 20971520
  pod:
    volumeMounts:
      - name: authconfig
        mountPath: /etc/nats-config/authconfig
  template:
    serviceAccountName: my-secrets-getting-sa
    initContainers:
      - name: secret-getter
        image: "busybox"
        command: ["sh", "-c", "echo 'users = [ { user: 'foo', pass: 'bar' } ]' > /etc/nats-config/authconfig/auth.json"]
        volumeMounts:
          - name: authconfig
            mountPath: /etc/nats-config/authconfig
    volumes:
      - name: authconfig
        emptyDir: {}
  auth:
    # Needs to be under /etc/nats-config where nats looks
    # for its config file, or it won't be able to be included
    # by /etc/nats-config/gnatsd.conf
    clientAuthFile: "authconfig/auth.json"
