apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "nats-cluster"
spec:
  size: 3

  useServerName: true

  template:
    spec:
      containers:
        - name: "nats"
          imagePullPolicy: "Always"
          restartPolicy: "Always"
          terminationMessagePolicy: "FallbackToLogsOnError"
          env:
            - name: "MY_NODE_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: "spec.nodeName"
            - name: "MY_POD_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.name"
            - name: "SERVER_NAME"
              value: us-$(MY_POD_NAME)
            - name: "MY_POD_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
          lifecycle:
            preStop:
              exec:
                command: ["preStop.sh"]
