apiVersion: "nats.io/v1beta1"
kind: "NatsCluster"
metadata:
  name: "nats"
spec:
  # Number of nodes in the cluster
  size: 3

  # Must use 1.0.4 in order to allow waiting for the A record
  # from nodes in the cluster to be ready
  version: "1.0.4"

  logging:
    debug: true
    trace: true

  tls:
    # Certificates to secure the NATS client connections:
    serverSecret: "nats-clients-tls"

    # Certificates to secure the routes.
    routesSecret: "nats-routes-tls"
