// Copyright 2017-2018 The nats-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/nats-io/nats-operator/pkg/apis/nats/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNatsServiceRoles implements NatsServiceRoleInterface
type FakeNatsServiceRoles struct {
	Fake *FakeNatsV1alpha2
	ns   string
}

var natsservicerolesResource = schema.GroupVersionResource{Group: "nats", Version: "v1alpha2", Resource: "natsserviceroles"}

var natsservicerolesKind = schema.GroupVersionKind{Group: "nats", Version: "v1alpha2", Kind: "NatsServiceRole"}

// Get takes name of the natsServiceRole, and returns the corresponding natsServiceRole object, and an error if there is any.
func (c *FakeNatsServiceRoles) Get(name string, options v1.GetOptions) (result *v1alpha2.NatsServiceRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(natsservicerolesResource, c.ns, name), &v1alpha2.NatsServiceRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.NatsServiceRole), err
}

// List takes label and field selectors, and returns the list of NatsServiceRoles that match those selectors.
func (c *FakeNatsServiceRoles) List(opts v1.ListOptions) (result *v1alpha2.NatsServiceRoleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(natsservicerolesResource, natsservicerolesKind, c.ns, opts), &v1alpha2.NatsServiceRoleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.NatsServiceRoleList{ListMeta: obj.(*v1alpha2.NatsServiceRoleList).ListMeta}
	for _, item := range obj.(*v1alpha2.NatsServiceRoleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested natsServiceRoles.
func (c *FakeNatsServiceRoles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(natsservicerolesResource, c.ns, opts))

}

// Create takes the representation of a natsServiceRole and creates it.  Returns the server's representation of the natsServiceRole, and an error, if there is any.
func (c *FakeNatsServiceRoles) Create(natsServiceRole *v1alpha2.NatsServiceRole) (result *v1alpha2.NatsServiceRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(natsservicerolesResource, c.ns, natsServiceRole), &v1alpha2.NatsServiceRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.NatsServiceRole), err
}

// Update takes the representation of a natsServiceRole and updates it. Returns the server's representation of the natsServiceRole, and an error, if there is any.
func (c *FakeNatsServiceRoles) Update(natsServiceRole *v1alpha2.NatsServiceRole) (result *v1alpha2.NatsServiceRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(natsservicerolesResource, c.ns, natsServiceRole), &v1alpha2.NatsServiceRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.NatsServiceRole), err
}

// Delete takes name of the natsServiceRole and deletes it. Returns an error if one occurs.
func (c *FakeNatsServiceRoles) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(natsservicerolesResource, c.ns, name), &v1alpha2.NatsServiceRole{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNatsServiceRoles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(natsservicerolesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha2.NatsServiceRoleList{})
	return err
}

// Patch applies the patch and returns the patched natsServiceRole.
func (c *FakeNatsServiceRoles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.NatsServiceRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(natsservicerolesResource, c.ns, name, pt, data, subresources...), &v1alpha2.NatsServiceRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.NatsServiceRole), err
}
