// Copyright 2017-2018 The nats-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha2 "github.com/nats-io/nats-operator/pkg/apis/nats/v1alpha2"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NatsServiceRoleLister helps list NatsServiceRoles.
type NatsServiceRoleLister interface {
	// List lists all NatsServiceRoles in the indexer.
	List(selector labels.Selector) (ret []*v1alpha2.NatsServiceRole, err error)
	// NatsServiceRoles returns an object that can list and get NatsServiceRoles.
	NatsServiceRoles(namespace string) NatsServiceRoleNamespaceLister
	NatsServiceRoleListerExpansion
}

// natsServiceRoleLister implements the NatsServiceRoleLister interface.
type natsServiceRoleLister struct {
	indexer cache.Indexer
}

// NewNatsServiceRoleLister returns a new NatsServiceRoleLister.
func NewNatsServiceRoleLister(indexer cache.Indexer) NatsServiceRoleLister {
	return &natsServiceRoleLister{indexer: indexer}
}

// List lists all NatsServiceRoles in the indexer.
func (s *natsServiceRoleLister) List(selector labels.Selector) (ret []*v1alpha2.NatsServiceRole, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.NatsServiceRole))
	})
	return ret, err
}

// NatsServiceRoles returns an object that can list and get NatsServiceRoles.
func (s *natsServiceRoleLister) NatsServiceRoles(namespace string) NatsServiceRoleNamespaceLister {
	return natsServiceRoleNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// NatsServiceRoleNamespaceLister helps list and get NatsServiceRoles.
type NatsServiceRoleNamespaceLister interface {
	// List lists all NatsServiceRoles in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha2.NatsServiceRole, err error)
	// Get retrieves the NatsServiceRole from the indexer for a given namespace and name.
	Get(name string) (*v1alpha2.NatsServiceRole, error)
	NatsServiceRoleNamespaceListerExpansion
}

// natsServiceRoleNamespaceLister implements the NatsServiceRoleNamespaceLister
// interface.
type natsServiceRoleNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all NatsServiceRoles in the indexer for a given namespace.
func (s natsServiceRoleNamespaceLister) List(selector labels.Selector) (ret []*v1alpha2.NatsServiceRole, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.NatsServiceRole))
	})
	return ret, err
}

// Get retrieves the NatsServiceRole from the indexer for a given namespace and name.
func (s natsServiceRoleNamespaceLister) Get(name string) (*v1alpha2.NatsServiceRole, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha2.Resource("natsservicerole"), name)
	}
	return obj.(*v1alpha2.NatsServiceRole), nil
}
