// Copyright 2017 The nats-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	spec "github.com/nats-io/nats-operator/pkg/spec"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeServiceRoles implements ServiceRoleInterface
type FakeServiceRoles struct {
	Fake *FakePkgSpec
	ns   string
}

var servicerolesResource = schema.GroupVersionResource{Group: "pkg", Version: "spec", Resource: "serviceroles"}

var servicerolesKind = schema.GroupVersionKind{Group: "pkg", Version: "spec", Kind: "ServiceRole"}

// Get takes name of the serviceRole, and returns the corresponding serviceRole object, and an error if there is any.
func (c *FakeServiceRoles) Get(name string, options v1.GetOptions) (result *spec.ServiceRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(servicerolesResource, c.ns, name), &spec.ServiceRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*spec.ServiceRole), err
}

// List takes label and field selectors, and returns the list of ServiceRoles that match those selectors.
func (c *FakeServiceRoles) List(opts v1.ListOptions) (result *spec.ServiceRoleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(servicerolesResource, servicerolesKind, c.ns, opts), &spec.ServiceRoleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &spec.ServiceRoleList{ListMeta: obj.(*spec.ServiceRoleList).ListMeta}
	for _, item := range obj.(*spec.ServiceRoleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested serviceRoles.
func (c *FakeServiceRoles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(servicerolesResource, c.ns, opts))

}

// Create takes the representation of a serviceRole and creates it.  Returns the server's representation of the serviceRole, and an error, if there is any.
func (c *FakeServiceRoles) Create(serviceRole *spec.ServiceRole) (result *spec.ServiceRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(servicerolesResource, c.ns, serviceRole), &spec.ServiceRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*spec.ServiceRole), err
}

// Update takes the representation of a serviceRole and updates it. Returns the server's representation of the serviceRole, and an error, if there is any.
func (c *FakeServiceRoles) Update(serviceRole *spec.ServiceRole) (result *spec.ServiceRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(servicerolesResource, c.ns, serviceRole), &spec.ServiceRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*spec.ServiceRole), err
}

// Delete takes name of the serviceRole and deletes it. Returns an error if one occurs.
func (c *FakeServiceRoles) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(servicerolesResource, c.ns, name), &spec.ServiceRole{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServiceRoles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(servicerolesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &spec.ServiceRoleList{})
	return err
}

// Patch applies the patch and returns the patched serviceRole.
func (c *FakeServiceRoles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *spec.ServiceRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(servicerolesResource, c.ns, name, data, subresources...), &spec.ServiceRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*spec.ServiceRole), err
}
