// Copyright 2017 The nats-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package spec

import (
	spec "github.com/nats-io/nats-operator/pkg/spec"
	scheme "github.com/nats-io/nats-operator/pkg/typed-client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ServiceRolesGetter has a method to return a ServiceRoleInterface.
// A group's client should implement this interface.
type ServiceRolesGetter interface {
	ServiceRoles(namespace string) ServiceRoleInterface
}

// ServiceRoleInterface has methods to work with ServiceRole resources.
type ServiceRoleInterface interface {
	Create(*spec.ServiceRole) (*spec.ServiceRole, error)
	Update(*spec.ServiceRole) (*spec.ServiceRole, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*spec.ServiceRole, error)
	List(opts v1.ListOptions) (*spec.ServiceRoleList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *spec.ServiceRole, err error)
	ServiceRoleExpansion
}

// serviceRoles implements ServiceRoleInterface
type serviceRoles struct {
	client rest.Interface
	ns     string
}

// newServiceRoles returns a ServiceRoles
func newServiceRoles(c *PkgSpecClient, namespace string) *serviceRoles {
	return &serviceRoles{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the serviceRole, and returns the corresponding serviceRole object, and an error if there is any.
func (c *serviceRoles) Get(name string, options v1.GetOptions) (result *spec.ServiceRole, err error) {
	result = &spec.ServiceRole{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("serviceroles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ServiceRoles that match those selectors.
func (c *serviceRoles) List(opts v1.ListOptions) (result *spec.ServiceRoleList, err error) {
	result = &spec.ServiceRoleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("serviceroles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested serviceRoles.
func (c *serviceRoles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("serviceroles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a serviceRole and creates it.  Returns the server's representation of the serviceRole, and an error, if there is any.
func (c *serviceRoles) Create(serviceRole *spec.ServiceRole) (result *spec.ServiceRole, err error) {
	result = &spec.ServiceRole{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("serviceroles").
		Body(serviceRole).
		Do().
		Into(result)
	return
}

// Update takes the representation of a serviceRole and updates it. Returns the server's representation of the serviceRole, and an error, if there is any.
func (c *serviceRoles) Update(serviceRole *spec.ServiceRole) (result *spec.ServiceRole, err error) {
	result = &spec.ServiceRole{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("serviceroles").
		Name(serviceRole.Name).
		Body(serviceRole).
		Do().
		Into(result)
	return
}

// Delete takes name of the serviceRole and deletes it. Returns an error if one occurs.
func (c *serviceRoles) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("serviceroles").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *serviceRoles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("serviceroles").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched serviceRole.
func (c *serviceRoles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *spec.ServiceRole, err error) {
	result = &spec.ServiceRole{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("serviceroles").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
