apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nats.fullname" . }}
{{- if and .Values.clusterScoped .Values.cluster.namespace }}
  namespace: {{ .Values.cluster.namespace }}
{{- end }}

  labels:
    app: {{ template "nats.name" . }}
    chart: {{ template "nats.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.updateStrategy }}
    {{- if eq .Values.updateStrategy "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdateMaxSurge }}
      maxUnavailable: {{ .Values.rollingUpdateMaxUnavailable }}
        {{- end }}
  selector:
    matchLabels:
      app: {{ template "nats.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "nats.name" . }}
        release: {{ .Release.Name }}
      {{- if .Values.podLabels }}
        {{ .Values.podLabels}}
      {{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{ .Values.podAnnotations }}
      {{- end }}
    spec:
      {{- if .Values.rbacEnabled }}
      serviceAccountName: nats-operator
      {{- end }}
      containers:
      - name: nats-operator
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy  }}
        {{- if .Values.clusterScoped }}
        args:
        - nats-operator
        - --feature-gates=ClusterScoped=true
        {{- end }}
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - name: readyz
          containerPort: 8080
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /readyz
            port: readyz
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: readyz
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10}}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName}}"
      {{- end }}
      {{- if eq .Values.antiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: "{{ template "nats.name" . }}"
                  release: {{ .Release.Name | quote }}
      {{- else if eq .Values.antiAffinity "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: "{{ template "nats.name" . }}"
                  release: "{{ .Release.Name }}"
      {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{ .Values.image.pullSecrets}}
      {{- end }}
