{{- if .Values.rbacEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-operator
{{- if and .Values.clusterScoped .Values.cluster.namespace }}
  namespace: {{ .Values.cluster.namespace }}
{{- end }}
{{- end }}
