FROM gcr.io/distroless/base

# Use the pre-built binary in "build/nats-operator-e2e" (i.e. the one generated by running "make build.e2e").
# This is done so we can take advantage of the local "vendor/" and "$GOCACHE/" directories, and makes skaffold re-deploy the application only when recompiled.
COPY build/nats-operator-e2e /nats-operator-e2e

CMD ["/nats-operator-e2e"]
