FROM gcr.io/distroless/base

# Use the pre-built binary in "build/nats-operator" (i.e. the one generated by running "make build.operator").
# This is done so we can take advantage of the local "vendor/" and "$GOCACHE/" directories, and makes skaffold re-deploy the application only when recompiled.
COPY build/nats-operator /nats-operator

ENV MY_POD_NAMESPACE default
ENV MY_POD_NAME nats-operator
EXPOSE 8080

CMD ["/nats-operator"]
