apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-operator
  namespace: __NAMESPACE__
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nats-operator-__NAMESPACE__
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nats-operator
subjects:
  - kind: ServiceAccount
    name: nats-operator
    namespace: __NAMESPACE__
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nats-operator
rules:
  # Allow creating CRDs
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs: ["*"]
  # Allow all actions on NatsClusters
  - apiGroups:
      - nats.io
    resources:
      - natsclusters
      - natsserviceroles
    verbs: ["*"]
  # Allow actions on basic Kubernetes objects
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
      - pods
      - pods/exec
      - pods/log
      - services
      - serviceaccounts
      - serviceaccounts/token
      - endpoints
      - events
    verbs: ["*"]
  # Allow creating, deleting and listing namespaces
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
      - delete
      - list
  # Allow listing and watching deployments (required by the end-to-end test suite).
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-server
  namespace: __NAMESPACE__
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nats-server-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nats-server
subjects:
- kind: ServiceAccount
  name: nats-server
  namespace: __NAMESPACE__
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nats-server
rules:
- apiGroups: [""]
  resources:
  - nodes
  verbs: ["get"]
