// Copyright 2017-2018 The nats-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	time "time"

	natsv1alpha2 "github.com/nats-io/nats-operator/pkg/apis/nats/v1alpha2"
	versioned "github.com/nats-io/nats-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/nats-io/nats-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha2 "github.com/nats-io/nats-operator/pkg/client/listers/nats/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NatsServiceRoleInformer provides access to a shared informer and lister for
// NatsServiceRoles.
type NatsServiceRoleInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha2.NatsServiceRoleLister
}

type natsServiceRoleInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewNatsServiceRoleInformer constructs a new informer for NatsServiceRole type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNatsServiceRoleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNatsServiceRoleInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredNatsServiceRoleInformer constructs a new informer for NatsServiceRole type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNatsServiceRoleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NatsV1alpha2().NatsServiceRoles(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NatsV1alpha2().NatsServiceRoles(namespace).Watch(options)
			},
		},
		&natsv1alpha2.NatsServiceRole{},
		resyncPeriod,
		indexers,
	)
}

func (f *natsServiceRoleInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNatsServiceRoleInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *natsServiceRoleInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&natsv1alpha2.NatsServiceRole{}, f.defaultInformer)
}

func (f *natsServiceRoleInformer) Lister() v1alpha2.NatsServiceRoleLister {
	return v1alpha2.NewNatsServiceRoleLister(f.Informer().GetIndexer())
}
